workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        ANDROID_KEYSTORE: "dummy.keystore"
        ANDROID_KEYSTORE_PASSWORD: "dummy_password"
        ANDROID_KEY_ALIAS: "dummy_alias"
        ANDROID_KEY_PASSWORD: "dummy_password"
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build debug APK
        script: ./gradlew assembleDebug
      - name: Build release APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
