workflows:
  android-workflow:
    name: Teclado Camaleón Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      java: 17
      xcode: latest
      
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
          
    scripts:
      - name: Setup Gradle Wrapper
        script: |
          chmod +x gradlew
          chmod +x gradlew.bat
          echo "Gradle wrapper configured"
          ./gradlew --version
          
      - name: Set up local properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          
      - name: Clean project
        script: |
          ./gradlew clean --stacktrace
          
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug --stacktrace
          
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
