workflows:
  android-workflow:
    name: Teclado Camaleón Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      java: 17
      xcode: latest
      cocoapods: default
      vars:
        PACKAGE_NAME: "com.chameleon.keyboard"
        
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
          
    scripts:
      - name: Set up local properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          
      - name: Grant permissions (safety measure)
        script: |
          chmod +x gradlew
          ls -la gradlew
          
      - name: Clean and build
        script: |
          ./gradlew clean assembleDebug --stacktrace
          
      - name: Run tests
        script: |
          ./gradlew test --stacktrace
          
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/mapping.txt
      
    publishing:
      email:
        recipients:
          - tu-email@ejemplo.com
        notify:
          success: true
          failure: true
