workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        # Variables de entorno opcionales, por ejemplo para firmar APK
        ANDROID_KEYSTORE: ""
        ANDROID_KEYSTORE_PASSWORD: ""
        ANDROID_KEY_ALIAS: ""
        ANDROID_KEY_PASSWORD: ""
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build debug APK
        script: ./gradlew assembleDebug
      - name: Build release APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
