workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      android:
        jdk: openjdk11
        compileSdk: 33
        buildTools: "33.0.2"
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build debug APK
        script: ./gradlew assembleDebug
      - name: Build release APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
